@extends('layouts.app')
@section('content')
    <!-- breadcrumb area -->
    <div class="breadcrumb-area bg-img pt-230 pb-152 default-overlay-2" style="background-image: url({{asset('public/images/bg/panel.jpg')}});background-size: cover">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <h2 class="text-uppercase">Solar Systems</h2>
            </div>
        </div>
    </div>
    <!-- main-search start -->
    <div class="works-area pt-215 pb-245">
        <div class="container">
            <div class="section-title text-center mb-78">
                <h2>Solar Panel</h2>
            </div>
            <div class="row d-flex align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="works-video-img mr-20">
                        <img src="{{asset('public/images/bg/panel.jpg')}}" alt="">
                        <div class="works-video">

                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="tools-content ml-20 text-dark">
                        <p style="font-size: 15px; font-weight: 500; line-height: 20px" class="mb-5  text-dark">
                            <strong style="font-size: 18px; ">Solar panel</strong> is a set of solar photovoltaic modules electrically connected & fixed on a structure to provide solar energy.
                        </p>

                        <p style="font-size: 15px; font-weight: 500; line-height: 20px" class="mb-5">
                            We are into Sales,Installation and Importation of renewable  energy proucts,which is an Alternative Energy source that  is aimed at ꞉
                        </p>
                        <ul class="list-unstyled">
                            • Increasing  Productivity
                            • Reducing  Operational Cost
                            • Increasing  Customer Satisfaction
                        </ul>

                        <h4 class="mt-42">Solar energy Benefit</h4>
                        <ul class="list-unstyled">
                            <li class="d-block">
                                - Using solar power helps reduce our energy reliance on fossil fuels.
                            </li>
                            <li class="d-block">
                                - The electricity generated by your solar power system is clean, renewable and reliable.
                            </li>
                            <li class="d-block">
                                - Solar power systems can provide owners with fixed energy costs.
                            </li>
                            <li class="d-block">
                                - Solar hot water systems save you money on your electricity.
                            </li>
                        </ul>

                        <p style="font-size: 18px; margin-top: 20px; font-weight: bold; line-height: 20px" class="mb-5">
                            Our focus is to urge businesses and organizations to stop implementing unsuccessful and expensive methods in other to ensure continuous flow of energy.
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection